### ISSUE TITLE
Time between each command call

### ISSUE THREAD

**Issue by xZett0** [okok7711/AminoAcid#1]
how about adding the ability to make a time sleep between each command call, in BotAmino if you assign a sleep time for command calls every single command will be sleeping for a certain user meaning if you use the command "say" then the command "dice" won't work until the sleep is done, so maybe make it flexible like each command has its own time sleep maybe assigned as an argument or a decorator.

**Comment by okok7711** [comment]
like a cooldown on per User or per Command basis?

**Comment by okok7711** [comment]
@xZett0 cooldowns can now be used on a per-user per-command basis
so if one user were to execute `say` and say had a cooldown of 10 they would only be able to call that command every 10 seconds

**Comment by xZett0** [comment]
> @xZett0 cooldowns can now be used on a per-user per-command basis so if one user were to execute `say` and say had a cooldown of 10 they would only be able to call that command every 10 seconds

nice i sometime before tried to do this thing to a bot i had i never completed it now i can learn from it, thanks, btw if you have time can you contact me on discord ? zett.0#6809
